name: apartment-manager-infra
description: AWS infrastructure for Apartment Manager SaaS
runtime:
  name: python
  options:
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: ""
